version: '3.9'

services:

  postgres:
    image: postgres:12.5
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-technical
    environment:
      - PORT=3000
      - DB_CLIENT_URL=postgresql://admin:admin@postgres:5432/mvp
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

volumes:
  db-data: {}
